# SPDX-License-Identifier: BSD-2-Clause
# Copyright 2018 Linaro Ltd.
# Copyright 2018 Arm Ltd.
%YAML 1.2
---
$id: "http://devicetree.org/meta-schemas/base.yaml#"
$schema: "http://json-schema.org/draft-07/schema#"
description: "Metaschema for devicetree binding documentation"

allOf:
  - $ref: "http://json-schema.org/draft-07/schema#"
  - $ref: "http://devicetree.org/meta-schemas/keywords.yaml#"

properties:
  # listing all properties here to narrow the scope of what is allowed in
  # devicetree schema files. This list can be relaxed in the future as we
  # become more comfortable with the validation vocabulary.
  # Also, being explicit about what properties are allowed helps to catch
  # misspelled or unsupported tests.
  $id:
    pattern: 'http://devicetree.org/schemas/.*\.yaml#'
  $schema:
    enum:
      - "http://devicetree.org/meta-schemas/core.yaml#"
      - "http://devicetree.org/meta-schemas/base.yaml#"
  title:
    maxLength: 100
  description: true
  examples:
    type: array
    items:
      type: string
  required: true
  allOf:
    items:
      propertyNames:
        enum:
          - $ref
          - if
          - then
          - else
  anyOf: true
  oneOf: true
  definitions: true
  additionalProperties: true
  dependencies: true
  patternProperties: true
  properties: true
  if: true
  then: true
  else: true
  unevaluatedProperties: true
  deprecated: true

  maintainers:
    type: array
    items:
      type: string
      format: email

  select:
    allOf:
      - $ref: "http://json-schema.org/draft-07/schema#"
      - oneOf:
          - type: object
            properties:
              properties: true
              required: true
          - type: boolean

required:
  - $id
  - $schema
  - title
  - maintainers

additionalProperties: false
