# SPDX-License-Identifier: BSD-2-Clause
# Copyright 2018 Linaro Ltd.
# Copyright 2018 Arm Ltd.
%YAML 1.2
---
$id: http://devicetree.org/meta-schemas/base.yaml#
$schema: https://json-schema.org/draft/2019-09/schema
description: Metaschema for devicetree binding documentation

allOf:
  - $ref: http://json-schema.org/draft-07/schema#
  - $ref: http://devicetree.org/meta-schemas/keywords.yaml#

properties:
  # listing all properties here to narrow the scope of what is allowed in
  # devicetree schema files. This list can be relaxed in the future as we
  # become more comfortable with the validation vocabulary.
  # Also, being explicit about what properties are allowed helps to catch
  # misspelled or unsupported tests.
  $id:
    pattern: 'http://devicetree.org/schemas/.*\.yaml#'
  $schema:
    enum:
      - "http://devicetree.org/meta-schemas/core.yaml#"
      - "http://devicetree.org/meta-schemas/base.yaml#"
  title:
    maxLength: 100
    description:
      Everything is a binding/schema, no need to say it. Describe what
      hardware the binding is for.
    not:
      pattern: '([Bb]inding| [Ss]chema)'

  examples:
    type: array
    items:
      type: string

  maintainers:
    type: array
    items:
      type: string
      format: email

  select:
    description: '"select" must contain a valid json-schema'
    allOf:
      - $ref: http://json-schema.org/draft-07/schema#
      - oneOf:
          - type: object
            properties:
              properties: true
              required: true
          - type: boolean

propertyNames:
  enum: [ $id, $schema, title, description, examples, required, allOf, anyOf, oneOf,
          definitions, $defs, additionalProperties, dependencies, dependentRequired,
          dependentSchemas, patternProperties, properties, not, if, then, else,
          unevaluatedProperties, deprecated, maintainers, select, $ref ]

required:
  - $id
  - $schema
  - title
  - maintainers
