#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
# Copyright 2018 Linaro Ltd.
# Copyright 2018 Arm Ltd.

import sys
import argparse
import ruamel.yaml
import json

yaml = ruamel.yaml.YAML()

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument('-o', '--output', nargs=1, help="output to specified file")

    ap.add_argument("file", type=str,
                    help="Filename of YAML encoded devicetree input file")
    args = ap.parse_args()

    yamldata = yaml.load(open(args.file, encoding='utf-8').read())
    if args.output and args.output[0]:
        f = open(args.output[0], 'w', encoding='utf-8')
    else:
        f = open(args.file.replace('.yaml', '.json'), 'w', encoding='utf-8')

    json.dump(yamldata, f)
