#!/usr/bin/env python3

import sys
import argparse
from ruamel import yaml

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("-i", "--in-place", help="operate in place on <file>",
                    action="store_true")

    ap.add_argument("file", type=str,
                    help="Filename of YAML encoded devicetree input file")
    args = ap.parse_args()

    yml = yaml.YAML()
    # Setup formatting settings
    yml.indent(mapping=2, sequence=4, offset=2)
    yml.explicit_start=True
    yml.preserve_quotes=True
    yml.version=(1,2)

    yamldata = yml.load(open(args.file).read())

    if args.in_place:
        f = open(args.file, 'w')
    else:
        f = sys.stdout

    yml.dump(yamldata, f)
